- src/joshuto/config.rs
- src/main.rs
> Cleanup config hierarchy; Only add ./config in debug mode

- .github/workflows/rust.yml
- README.md
This pull request aims integrate Github Actions for Testing.
> Github workflows and Test Badge.

- Cargo.lock
- Cargo.toml
- config/mimetype.toml
- src/commands/key_command.rs
- src/main.rs
- src/ui/views/tui_progress_view.rs
#33 
I've added tilde expansion in the cd command. I also fixed an issue with the default mimetype config file.
> cd with tilde expansion

- src/ui/widgets/tui_worker.rs
> show visual progress bar in worker view

- config/mimetype.toml
Oops should have checked here too :/
> Add support for .webp in mimetype.toml

- src/ui/widgets/tui_dirlist_detailed.rs
I left `MIN_LEFT_LABEL_WIDTH` at 15.
> fix: right label disappears

- src/ui/widgets/tui_topbar.rs
Hi!
shortens the path when it is longer than area.width. I'm not sure if it's in a good place as I'm not an experienced programmer and I'm a newbie in rust.
> Path shortener

- src/commands/open_file.rs
- src/context/app_context.rs
- src/main.rs
- src/run.rs
Not sure if this is the best way to implement it, but I've been sitting on various iterations of this hack for a while now. I think it would close https://github.com/kamiyaa/joshuto/issues/96.
> Add choosefiles feature

- src/commands/numbered_command.rs
- src/event/app_event.rs
- src/run.rs
- src/ui/mod.rs
- src/ui/tui_backend.rs
- src/ui/views/mod.rs
- src/ui/views/tui_command_menu.rs
- src/ui/views/tui_folder_view.rs
- src/ui/views/tui_textfield.rs
- src/ui/views/tui_view.rs
- src/ui/widgets/tui_file_preview.rs
- src/ui/widgets/tui_prompt.rs
As mentioned in https://github.com/kamiyaa/joshuto/pull/113
> refactor image preview via ueberzug

- docs/image_previews.md
Include documentation on how to get image previews with Kitty.
> Add Kitty image previews to docs

- src/context/app_context.rs
So that the code is more readable
> Remove boilerplate

- config/joshuto.toml
- config/preview_file.sh
- docs/configuration/joshuto.toml.md
- src/config/general/display_crude.rs
- src/config/general/preview_crude.rs
- src/config/keymap/keymapping.rs
- src/config/option/display_option.rs
- src/config/option/preview_option.rs
- src/context/preview_context.rs
- src/fs/entry.rs
- src/preview/preview_default.rs
- src/preview/preview_dir.rs
- src/preview/preview_file.rs
- src/run.rs
- src/ui/tui_backend.rs
- src/ui/widgets/tui_file_preview.rs
Remove dead code and unused imports around preview features.
> code cleanup

- src/ui/views/tui_textfield.rs
Add shortcuts such as Ctrl+W, Ctrl+D, etc. to the textfield.
Also make auto completion work a bit better by moving cursor and then trying to complete instead of splitting the word in two.
> Console shortcuts

- src/commands/open_file.rs
- src/config/mimetype/entry.rs
- src/fs/dirlist.rs
Resolves https://github.com/kamiyaa/joshuto/issues/147
> Try all options when opening files

- src/config/theme/style.rs
Consulted with a friend who knows Rust better than me and was able
to implement a fix for #151 pretty quickly after that point.
also thanks for having 2 different Rgb libraries active at the same time lmao
> Fix for issue #151

- Cargo.lock
- src/ui/widgets/tui_dirlist.rs
- src/ui/widgets/tui_dirlist_detailed.rs
- src/util/style.rs
- fix color not applying to entire row
> fix regular file styling not respecting theme config

- src/context/app_context.rs
Along with https://github.com/notify-rs/notify/pull/399 this fixes build on FreeBSD.
> Use notify::RecommendedWatcher to simplify code and support BSD platforms

- config/keymap.toml
Pretty much like everywhere else on linux
Awesome project, I just discovered it :heart:
> add ctrl+h as hidden files toggle

- Cargo.lock
- Cargo.toml
- docs/configuration/keymap.toml.md
- src/commands/bulk_rename.rs
- src/commands/flat.rs
- src/commands/mod.rs
- src/commands/open_file.rs
- src/commands/show_tasks.rs
- src/fs/entry.rs
- src/key_command/command.rs
- src/key_command/constants.rs
- src/key_command/impl_appcommand.rs
- src/key_command/impl_appexecute.rs
- src/key_command/impl_comment.rs
- src/key_command/impl_from_str.rs
> Add `flat` command

- src/commands/zoxide.rs
> Support multiple patterns in zoxide

- src/ui/views/tui_folder_view.rs
- src/ui/views/tui_hsplit_view.rs
- src/ui/widgets/tui_footer.rs
Added footer indicators for filter and flat commands, to display current value if set.
> Display filter and flat status in footer

- src/commands/delete_files.rs
Hi. Directory preview removal on folder remove #89
> remove from history by dir paths

- Cargo.lock
- Cargo.toml
- src/ui/widgets/tui_file_preview.rs
- src/ui/widgets/tui_footer.rs
- src/ui/widgets/tui_tab.rs
- src/ui/widgets/tui_topbar.rs
Solve this issue : https://github.com/kamiyaa/joshuto/issues/318
> fix(spans,line): update dependency ratatui 0.21

- src/commands/command_line.rs
- src/context/app_context.rs
- src/ui/views/tui_textfield.rs
Simply just cleaning up some warnings on build
> chore: cleanup warnings

- config/preview_file.sh
> Separate OpenOffice preview cases

- src/main.rs
- src/ui/widgets/tui_footer.rs
- src/util/format.rs
the files modified time will display with local timezone.
fix the issue #379 
change dev to main(#383 )
> feat: mtime will display with local timezone

- Cargo.lock
- Cargo.toml
- config/joshuto.toml
- docs/configuration/joshuto.toml.md
- docs/configuration/keymap.toml.md
- src/commands/case_sensitivity.rs
- src/commands/mod.rs
- src/commands/search_regex.rs
- src/config/general/search_raw.rs
- src/config/option/search_option.rs
- src/context/matcher.rs
- src/error/error_kind.rs
- src/error/error_type.rs
- src/key_command/command.rs
- src/key_command/constants.rs
- src/key_command/impl_appcommand.rs
- src/key_command/impl_appexecute.rs
- src/key_command/impl_comment.rs
- src/key_command/impl_display.rs
- src/key_command/impl_from_str.rs
Search files using regex pattern.
> feat: regex support

- docs/configuration/keymap.toml.md
- src/commands/rename_file.rs
- src/key_command/command.rs
- src/key_command/constants.rs
- src/key_command/impl_appcommand.rs
- src/key_command/impl_appexecute.rs
- src/key_command/impl_comment.rs
- src/key_command/impl_from_str.rs
This command renames a file with the cursor set to the end of the file name.
> feat: Add rename_file_append_ext command

- docs/image_previews/kitty.md
Use `ffmpegthumbnailer` to generate a preview for videos just like ranger does
> Add thumbnail for video preview on kitty

- src/config/raw/theme/style.rs
- src/ui/tab_list_builder.rs
Those clippy errors were bothering me... :sweat_smile:
> fix: resolve clippy errors

- src/ui/views/tui_textfield.rs
This doesn't implement #180 (which I'd like to start working on), but at least makes path autocompletion usable.
> fix: path autocompletion

- src/main.rs
> fix: hey use username not real name :D

- Cargo.lock
- Cargo.toml
- src/types/state/preview_state.rs
Should bring in some improvements like tmux support.
Also align `image` dependency to `allmytoes`'.
> update ratatui-image to 1.0.5

- src/commands/cursor_move.rs
- src/config/app.rs
This fixes current ci issues with clippy.
> Fix various small clippy issues

- config/joshuto.toml
- src/commands/mod.rs
- src/commands/set_display_mode.rs
- src/constants/command_name.rs
- src/types/command/impl_appcommand.rs
- src/types/command/impl_appexecute.rs
- src/types/command/impl_comment.rs
- src/types/command/impl_completion.rs
- src/types/command/impl_from_str.rs
- src/types/command/mod.rs
- src/types/option/display.rs
- src/ui/views/mod.rs
- src/ui/views/tui_minimal_view.rs
- src/ui/views/tui_view.rs
This adds a command `set_display_mode` to change the display mode at runtime.
Note my other PR #571 which this PR is based on, so the other should be reviewed and merged first for a cleaner diff. Thanks!
> Set display mode command

- config/preview_file.sh
> add `bat` as fallback for HTML and JSON preview

- config/theme.toml
> update default foreground colour for files to be compatible with different terminal themes
