src/joshuto/config.rs
src/joshuto/config/config.rs
src/joshuto/config/keymap.rs
src/joshuto/config/mimetype.rs
src/joshuto/config/theme.rs

So currently joshuto doesn't work unless the config files are copied from `./config` to `~/.config/joshuto`, since no keybinds are enabled. This PR loads default config files from `./config` if there isn't one in `~/.config/joshuto/`. I also refactored out the `read_config` function from all the config parsing files in the process.
edit: This also adds the `search_config_hiearchy` function, which can be expanded in the future if other config file locations are desired.

Refactor config parsing and add ./config to config hierarchy

---

src/util/unix.rs

I was seeing build errors due to attempting to bitwise-and a u32 and a u16:
```
error[E0308]: mismatched types
--> src/util/unix.rs:6:50
|
6 |     LIBC_PERMISSION_VALS.iter().any(|val| mode & *val != 0)
|                                                  ^^^^ expected `u32`, found `u16`
error[E0277]: no implementation for `u32 & u16`
--> src/util/unix.rs:6:48
|
6 |     LIBC_PERMISSION_VALS.iter().any(|val| mode & *val != 0)
|                                                ^ no implementation for `u32 & u16`
|
= help: the trait `std::ops::BitAnd<u16>` is not implemented for `u32`
```
I fixed this by simply up-converting `*val` to a `u32`.
The widening won't have any effect on functionality because we don't care about any of the higher bits.
(probably) Fixes #22

Fix bitwise-and build issues on macOS

---

Cargo.lock
src/ui/views/tui_folder_view.rs

This makes the rendering of  borders of tui_folder_view more consistent with that of ranger or lf.

Fix rendering of inner borders.

---

src/commands/bulk_rename.rs

A while after I do multiple bulk renames the screen becomes really messy containing files from previous bulk renames. This is a very simple fix. Maybe this could be improved a bit.

Clear the Screen Before Bulk Renaming

---

src/commands/key_command.rs
src/commands/mod.rs
src/commands/shell.rs
src/commands/sub_process.rs

As discussed in  #69, this PR adds a `spawn` command.
When executing a command with spawn, stdout and stderr of the executed sub-process are swallowed, so they don't mess up Joshuto's UI.

Add spawn command

---

config/keymap.toml
src/config/keymap/keymapping.rs

Beside opening the command line with a semi-colon, it can be opened also
with a colon. The default key mapping has been adapted as well as the
keymap.toml configuration template.

open command line with a colon

---

Cargo.lock
Cargo.toml
src/fs/metadata.rs
src/fs/mod.rs
src/ui/widgets/mod.rs
src/ui/widgets/tui_dirlist.rs
src/ui/widgets/tui_dirlist_detailed.rs
src/ui/widgets/tui_footer.rs
src/util/mod.rs
src/util/string.rs
src/util/style.rs

This PR is the first part of #71. It does not contain the directory size feature, but it includes:
* Show symlinked dirs like dirs, with a directory devicon
* Show size of target file for symlinked files in conbination with the “symlink arrow”
* Show permission flags of target file for symlinked files
This PR is much more invasive than I expected. Sorry for that. But when I started to combine the “symlink arrow” with the file size, one change led to the next. 
The massive change is mostly because of the calculation of the entry strings to display, which is now done in separate functions without using the `buf.set_stringn` method to handle the truncation of strings.
The good thing is that the code is more testable and easier to extend, for my feeling. A downside might be that the string …

Show symlinked files and dirs correctly

---

src/fs/dirlist.rs
src/ui/widgets/tui_dirlist.rs
src/ui/widgets/tui_dirlist_detailed.rs
src/util/input.rs

This PR fixes two bugs related to selecting entries with a left-mouse-click which appeared when borders are enabled.
It also adds a tiny code enhancement by putting the calculation of the “paging” into one central place, where it can be changed/enhanced/maintained more easily.

Fix selecting an entry by mouse click when show_borders=true

---

src/fs/metadata.rs
src/ui/widgets/tui_dirlist_detailed.rs

The middle column shows the size of directories in terms of contained
files and sub-directories in the right label for each entry.
Invalid symlinks and hidden files/dirs are included in the count.

show size of directories

---

config/theme.toml
src/config/theme/app_theme.rs
src/fs/metadata.rs
src/ui/widgets/tui_dirlist_detailed.rs
src/ui/widgets/tui_footer.rs
src/util/style.rs

Dangling symlinks are shown with a separate style. `theme.toml` has been extended with a `[link_invalid]` section. The default style is red+bold.
Furthermore, the link target, which is shown in the footer for a selected symlink, uses either the “link” style or the ”link_invalid” style respectively.
Merge request for `dev` branch as I saw that a symlink related commit was already on that branch. 
We can close #71 then. :wink:

highlight invalid symlinks

---

src/commands/file_ops.rs

Expected:
`/tmp/My long spaced file name.txt`
Actual:
`/tmp/Mylongspacedfilename.txt`

Fix: spaces being trimmed when copying files/paths

---

Cargo.lock

Hi there. I'm the maintainer of the [joshuto](https://ports.macports.org/port/joshuto/details/) port over at [MacPorts](https://www.macports.org).
MacPorts usually builds projects written in rust using the --frozen flag by first downloading the necessary dependencies. This way the cargo builds the project without access to the internet.
I noticed that the last two versions of joshuto have an incorrect Cargo.lock file in the tag. So I am forced to regenerate Cargo.lock and apply it as the patch. My request would be to regenerate Cargo.lock before releasing the new version.
Thanks for this great project!

version bump to 0.9.1 in Cargo.lock with cargo

---

Cargo.lock
Cargo.toml
src/ui/widgets/tui_file_preview.rs

Add ANSI color codes support in file preview using [ansi-to-tui](https://github.com/uttarayan21/ansi-to-tui) as suggested [here](https://github.com/fdehau/tui-rs/issues/304#issuecomment-827124643)
In `preview.sh`
```bash
jq --color-output . "${path}" && exit 0
bat --color=always --style="plain" -- "${path}" && exit 0
```
using `highlight` doesn't seem to work :(
related #67

Add ANSI color codes support in file previews

---

config/joshuto.toml
docs/README.md
docs/configuration/joshuto.toml.md
docs/configuration/keymap.toml.md
docs/misc.md
src/commands/line_nums.rs
src/commands/mod.rs
src/commands/numbered_command.rs
src/config/general/display_crude.rs
src/config/option/display_option.rs
src/key_command/command.rs
src/key_command/constants.rs
src/key_command/impl_appcommand.rs
src/key_command/impl_appexecute.rs
src/key_command/impl_comment.rs
src/key_command/impl_from_str.rs
src/key_command/impl_numbered.rs
src/key_command/mod.rs
src/key_command/traits.rs
src/run.rs
src/ui/views/tui_folder_view.rs
src/ui/widgets/tui_dirlist_detailed.rs

closes #41
Adds numbers for every entry in the main window. Supports both absolute numbering (As shown on the first screenshot in the linked issue), and relative numbering (As shown on the second screenshot, again, see the issue)
Work in progress:
- Refactoring and improving the code
- Adding documentation

add line numbers

---

src/commands/open_file.rs
src/commands/tab_ops.rs
src/fs/dirlist.rs

1st commit: Fix: `JoshutoDirList::need_update` does not only consider explicit deprecation but also a changed mtime from the file system.
2nd commit: update also the left (parent dir) pane when switching tab
3rd commit: soft-reload also when opening a directory

Fix: DirList::need_update considers mtime change

---

config/joshuto.toml
docs/configuration/joshuto.toml.md
src/config/general/display_crude.rs
src/ui/views/tui_folder_view.rs
src/ui/widgets/tui_dirlist.rs

closes #104
Changes behavior of `column_ratio` property in **joshuto.toml**, now it can have length of 2 or 3. If it has length of 2 or first value is 0, parent view won't be displayed

add dynamic number of columns

---

Cargo.lock
Cargo.toml
src/context/app_context.rs
src/event/app_event.rs
src/run.rs
src/util/input.rs

AppContext owns an INotifyWatcher, which watches the visible directories
(max. three). The list of directories to watch is updated on every
event. If a filesystem change is announced, a "soft-update" of the
current view is issued.

Update view on filesystem changes

---

docs/configuration/joshuto.toml.md
src/commands/change_directory.rs
src/commands/cursor_move.rs
src/commands/parent_cursor_move.rs
src/commands/search_glob.rs
src/commands/search_string.rs
src/commands/subdir_fzf.rs
src/commands/tab_ops.rs
src/context/app_context.rs
src/fs/dirlist.rs
src/history.rs
src/preview/preview_default.rs
src/run.rs
src/tab.rs
src/ui/widgets/tui_dirlist.rs
src/ui/widgets/tui_dirlist_detailed.rs
src/ui/widgets/tui_footer.rs
src/util/input.rs

The scrolling behavior is changed from “paging” to a continuous
scrolling. Joshuto keeps a buffer from the cursor to each end of the
list, which is configured by `[display] scroll_offset`. If the terminal
height is too small to keep the distance, the buffer is set to a value
that assures that the cursor is at least as close to the end the user is
scrolling towards as to the other end of the visible list.
If the window is resized and the cursor jumps out of scope, the viewport
is adjusted when changing the index next time.
Possible improvements:
* Issue a viewport update on terminal geometry change
* When scrolling down to the bottom, don't allow an empty section
beneath the last entry

Continuous scrolling 

---

src/run.rs

When the preview disappears, the "shown" hook script was spawned instead
of the "removed" hook script.
This mistake was not obvious with the preview-image recipe from the docs
which works also with the shown-script on remove.

Fix: invoke correct hook script

---

src/commands/help.rs
src/context/app_context.rs
src/run.rs

Moved the per-main-loop-cycle logic to AppContext to provide a flexible way to "inhibit" the preview by calling the removed-hook. The next cycle in the main loop will restore the preview.

Calling preview removed hook when help page shown

---

src/context/app_context.rs

When the size of the preview area changes, the "preview shown hook" is
called to give a chance to update the size and/or position of the
preview image.

Update external preview on geometry change

---

src/context/app_context.rs

The preview-removed-hook was called in each main loop cycle if no
preview area was shown and a removed-hook was configured.

fix: disarm spawn bomb

---

docs/image_previews.md

When changing from an image file to another file type, the last image
was not cleared with the given description.

fix doc of shown-hook for icat

---

src/key_command/constants.rs
src/ui/views/tui_textfield.rs

Good day! Some commands are multi word, say, `sort reverse`,  so this commit won't be able to autocomplete those after a space is pressed. 
To solve this we can either append those command matches to a `FilenameCompleter`, or make all commands to be one word only.
Also I don't like how constants need to be specified twice now, it can be improved with a macro, but I wonder whether there is a more general solution.

Autocomplete first words as commands

---

src/fs/dirlist.rs

Viewport index was overflowing. I found the problem when I tried to navigate a folder with more than 2^15 files in it

Viewport overflow

---

config/keymap.toml
src/commands/cursor_move.rs
src/commands/help.rs
src/key_command/command.rs
src/key_command/impl_appcommand.rs
src/key_command/impl_appexecute.rs
src/key_command/impl_comment.rs
src/key_command/impl_from_str.rs
src/ui/views/tui_textfield.rs

`ctrl+d` and `ctrl+u` are used in vim to move half page down and up accordingly. Add support for the same thing.

Move half page

---

.Dockerignore
Dockerfile

Not sure if it's useful but the Dockerfile compiles joshuto in a rust container and copy the binary into a busybox image. It results in a slim image with joshuto. 
Instructions: 
``` bash 
docker build -t joshuto:0.9.2 . 
``` 
``` bash 
docker run --rm -it -u $(id -u):$(id -g) -v $(pwd):/root joshuto:0.9.2 
``` 
And inside the container: 
``` bash 
joshuto 
```

Add docker to build the binary and copy it to a clean busybox image

---

Dockerfile

Sorry! I forgot to double check 😕

Fixed copy instruction to use the binary from the builder container

---

docs/configuration/keymap.toml.md

Some system doesn't come with `/tmp/$USER` by default.

docs: fix joshuto function

---

src/commands/file_ops.rs

Hi, 
I have xclip installed on my MacOS and it hangs during path copy. Use the clipboard library for better cross platform support.

use cli-clipboard for path copy

---

rustfmt.toml

Without this file, rustfmt's configuration might be coming from a developer's global configuration for rustfmt. To ensure consistency, we define an empty rustfmt configuration. This is explained upstream:
> Rustfmt is designed to be very configurable. You can create a TOML file called `rustfmt.toml` or `.rustfmt.toml`, place it in the project or any other parent directory and it will apply the options in that file. If none of these directories contain such a file, both your home directory and a directory called `rustfmt` in your [global config directory](https://docs.rs/dirs/1.0.4/dirs/fn.config_dir.html) (e.g. `.config/rustfmt/`) are checked as well.

Use rustfmt defaults

---

Cargo.lock
Cargo.toml
src/ui/widgets/tui_file_preview.rs

`ansi-to-tui` 0.6 uses the latest `tui`

Bump `ansi-to-tui` to `0.6` and remove `tui_old`

---

src/commands/change_directory.rs
src/commands/delete_files.rs
src/commands/flat.rs
src/commands/new_directory.rs
src/commands/reload.rs
src/commands/rename_file.rs
src/commands/sort.rs
src/commands/tab_ops.rs
src/commands/touch_file.rs
src/config/general/app.rs
src/config/general/display_raw.rs
src/config/option/display_option.rs
src/event/process_event.rs
src/fs/dirlist.rs
src/history.rs
src/preview/preview_dir.rs
src/tab.rs

Sort options (sort criterion, reversion, dir-first, and case-sensitivity)
are specific for each tab. Changing sort-options will not have any
affect on tabs other than the currently active one. Each new tab will
start with the default sort-options.

Sort options individual per tab

---

Cargo.lock
Cargo.toml
src/commands/bulk_rename.rs
src/commands/change_directory.rs
src/commands/delete_files.rs
src/commands/flat.rs
src/commands/new_directory.rs
src/commands/open_file.rs
src/commands/reload.rs
src/commands/show_hidden.rs
src/commands/sort.rs
src/commands/sub_process.rs
src/commands/tab_ops.rs
src/context/tab_context.rs
src/event/process_event.rs
src/run.rs
src/tab/homepage.rs
src/tab/mod.rs
src/tab/tab_struct.rs
src/ui/views/tui_folder_view.rs
src/ui/views/tui_hsplit_view.rs

This is preliminary changes in order to track preview threads and progress.
The current setup is we just kick off a new thread to load
the given directory whenever we see the directory content
does not exist in history.
We don't track these threads or which tab these requests
came from. When the result is returned, we just assign it
to the current tab, instead of the tab that actually
initiated the request.
By adding uuid, we can now track which tab requested the
preview and assign it accordingly.
This will also allow us to track the status of the preview,
so we can display to the user a loading state,
when a directory is taking longer than usual to load.
This will also solve the problem of kicking off multiple
threads to read the same directory for the same tab.
Now these threads can be …

use hashmap and uuid to store tabs

---

src/ui/views/tui_hsplit_view.rs

Closes: #202 
Setting `mode` to `"hsplit"` in **joshuto.toml** caused Joshuto to crash with "index out of bounds" error. This pull makes it function like before - if second tab is not opened, only tab on the left will be displayed

fix bug when HSplit view caused Joshuto to crash

---

docs/misc.md
src/event/process_event.rs

This enhances the mouse control and makes it similar to the behavior of ranger.
* Entries in the “child-panel” can also “be clicked” now.
* Left-clicking entries in the parent or child-panel moves the containing dir to the middle panel.
* Right-clicking entries in the parent or middle panel opens the entry.
This feature does not work properly in `hsplit`-mode.
A short user documentation has been added to `misc.md`.

Add ranger-like mouse control, incl. opening files

---

Cargo.lock
Cargo.toml
src/ui/widgets/tui_file_preview.rs

updated ansi-to-tui to 2.0.0 which has much better ansi parsing.
ansi-to-tui 0.6.0:
ansi-to-tui 2.0.0:

update ansi-to-tui to 2.0.0

---

docs/configuration/keymap.toml.md
src/commands/escape.rs
src/commands/filter.rs
src/commands/flat.rs
src/commands/reload.rs
src/config/general/display_raw.rs
src/config/option/display_option.rs
src/config/option/linemodes.rs
src/fs/entry.rs
src/history.rs
src/key_command/impl_from_str.rs
src/ui/views/tui_textfield.rs

- `filter` and `flat` commands are now specific to directory list and refreshing wouldn't reset the commands.
- Pressing "backspace" now updates on interactive commands.

Rework filter and flat commands to be dirlist specific

---

docs/configuration/keymap.toml.md

* Better description for `spawn` and `shell`, now mentioning `%s` and with “%s-examples”.
* Describe `toggle_visual` and `escape`.
* Few random, tiny enhancements

Enhace keymap docs (incl. shell & toggle_visual)

---

docs/configuration/keymap.toml.md
src/commands/rename_file.rs
src/key_command/command.rs
src/key_command/constants.rs
src/key_command/impl_appcommand.rs
src/key_command/impl_appexecute.rs
src/key_command/impl_comment.rs
src/key_command/impl_from_str.rs

Added the `rename_keep_ext` command as discussed in #214.
Refactoring: removed unnecessary code duplication with helper function `_get_current_file_name` and added some match statements for cleaner code (e.g. a `None => {}` more clearly indicates that nothing should be done in that case).

Added `rename_keep_ext` command and refactored rename functions

---

src/commands/bulk_rename.rs
src/fs/dirlist.rs

If no file is selected, bulk-rename will use the "current" file (the one with the cursor) for renaming.
Adds method `JoshutoDirList.selected_or_current -> Vec<&JoshutoDirEntry>` which can be used anywhere to get this a collection of selected files _or_ the current one if none is selected.

Bulk-rename works with only current file

---

docs/configuration/keymap.toml.md
src/commands/delete_files.rs
src/key_command/command.rs
src/key_command/impl_appexecute.rs
src/key_command/impl_display.rs
src/key_command/impl_from_str.rs

Add the `--permanently` option to the `delete_files` command to delete files permanently when `use_trash` is `true`.

Add option to override deleting to trash

---

src/key_command/impl_comment.rs

Subject says it all, a minor bug

Fix typo in help page "Swith" -> "Switch"

---

src/ui/widgets/tui_help.rs

I'm new to joshuto so use the Help view.
Currently when searching in the help using '/' it searches only the key and command columns. I actually need the search to search in the 'Description' column. 
So I modified the search code to search also in the Description column and do a case insensitive search.

Help search also inside description column

---

config/keymap.toml
docs/configuration/keymap.toml.md
src/commands/tab_ops.rs
src/config/option/mod.rs
src/config/option/new_tab_option.rs
src/key_command/command.rs
src/key_command/impl_appcommand.rs
src/key_command/impl_appexecute.rs
src/key_command/impl_comment.rs
src/key_command/impl_from_str.rs

The `new_tab` command got enhanced and can now open a user-specified directory, or the directory of the current tab, or the directory currently highlighted by the cursor.
* `new_tab some-dir` opens new tab with directory `some-dir`
* `new_tab --current` opens new tab with the same directory as the current tab
* `new_tab --cursor` opens new tab with the directory which is currently marked by the cursor
The `keymap.toml` documentation got adapted accordingly.
The default key-map also got enhanced/changed:
* `ctrl-t`: opens tab in default directory
* `shift-t`: opens tab in directory of current tab
* `alt-t`: opens tab in directory marked by cursor
Like before, all new tabs get activated when created. Opening tabs “in the background” is a possible enhancement for the future and might be …

new_tab can open specific directories

---

Cargo.lock
Cargo.toml
src/ui/views/tui_folder_view.rs
src/ui/views/tui_hsplit_view.rs

#289 
This changes the tui depedency to the ratatui package and makes the versioning less permissive since breaking changes are likely coming on minor versions
This version of ratatui (0.20.1) should have parity with tui, thought it looks like there are some type issues that i had to fix as well. 
I tested this just by hopping into joshuto and going between files and dirs, opened a file using it, and creating some tabs. If there are more manual tests i should run lemme know. 
tested on 6.3.1-arch1-1

change dependency from tui to ratatui

---

config/preview_file.sh
src/preview/preview_file.rs

Removed ranger residuals and dead code from the preview.sh script and the logic that invokes it.

Cleanup preview.sh template

---

docs/configuration/keymap.toml.md

Fix typo in keymap.toml.md

---

src/commands/subdir_fzf.rs

Fixed issue #300.
`fzf` command will call `FZF_DEFAULT_COMMAND` by default when input is tty. Therefore no need to call it in joshuto.

fix: `subdir_fzf` stuck on large directory.

---

config/theme.toml
docs/configuration/theme.toml.md
src/config/theme/app_theme.rs
src/config/theme/style.rs
src/ui/widgets/tui_tab.rs

Text style for tabs can be configured within
`theme.toml` with the dotted keys `tab.active` and `tab.inactive`.
The default style is the same as the former hard-coded style.
`theme.toml` has been restructured and comments have been added to give a short documentation on each style item.
The documentation (`theme.toml.md`) has been enhanced, and the excerpt of `theme.toml` with additional comments has been removed from there.
That way it should be easier for devs to keep docs and the default `theme.toml` in sync, and easier for users when the detail comments can be found in the configuration file itself.
The conversion from `AppStyle` to `tui::style::Style` is now provided as a function of `AppStyle` and a `From`-implementation for `Style` to avoid having the same factory code repeating …

Tab theme configurable

---

config/joshuto.toml
docs/configuration/joshuto.toml.md

When I follow the default config files in `/config/joshuto.toml`, I find the field [method](https://github.com/kamiyaa/joshuto/blob/6cb151ea4b58d006cfc52f54d52be05110bd5b90/config/joshuto.toml#L27C19-L27C19) which decides how to sort items doesn't work. It's because the default name of it in source code is [sort_method](https://github.com/kamiyaa/joshuto/blob/6cb151ea4b58d006cfc52f54d52be05110bd5b90/src/config/general/sort_raw.rs#L20C8-L20C8).

Fix incorrect sort method field in example config 

---

src/ui/views/tui_folder_view.rs

File previews load pretty quickly. Adjusting constraints during loading state made the file sizes flicker on the right side of my screen due to the rapidly growing and shrinking center column. This change keeps the columns a consistent size when highlighting new items making the application a bit easier on the eyes.

refactor: avoid changing constraints during PreviewFileState load

---

docs/image_previews/combined_with_text.md

Fixed a “bug” in the recipe for combining text and image previews. Images at a location whose path contains a space were not shown with the calculated y-offset.

Fix docs for combined text and image preview

---

docs/configuration/joshuto.toml.md
src/commands/command_line.rs
src/config/general/app.rs
src/config/general/app_raw.rs

I think it can be handy to have the ability to set custom command aliases (such as `:q` aliased to `:quit`), so I added a really simple implementation with a `HashMap`, which works fine for this task. For configuration I chose to put it in the main `joshuto.toml` because it's optional and if specified, the list isn't likely to be really long.
Let me know if it's a welcome feature or if there's something you would do differently.

feat: Add support for command aliases

---

config/keymap.toml
src/commands/file_ops.rs
src/key_command/command.rs
src/key_command/impl_appcommand.rs
src/key_command/impl_appexecute.rs
src/key_command/impl_comment.rs
src/key_command/impl_from_str.rs

`copy_filepath` command can now have `--all-selected` field for copying file paths for currently selected files.

added all_selected field in CopyFilePath

---

docs/configuration/keymap.toml.md
src/commands/delete_files.rs
src/key_command/command.rs
src/key_command/impl_appexecute.rs
src/key_command/impl_display.rs
src/key_command/impl_from_str.rs

Sometimes having to confirm every file deletion can be annoying, especially if `use_trash` is enabled, so I added this option to skip the prompt.
In `commands/delete_files.rs` I moved the prompt part in a separate function so that it's easier to skip, and left in the `delete_files` function only the part that actually deletes the files.

feat: add `noconfirm` option to `delete_files` command

---

.github/workflows/automated-build.yml

This PR addresses the macOS build failure in the automated build process. The issue was caused by [deprecated](https://github.blog/changelog/2022-07-20-github-actions-the-macos-10-15-actions-runner-image-is-being-deprecated-and-will-be-removed-by-8-30-22/) versions.
After merging this pull request, note that the macOS binary could be attached to the current release by [re-running all jobs](https://docs.github.com/en/actions/managing-workflow-runs/re-running-workflows-and-jobs) or the failed one.

Fix: macos build on automated-build

---

Cargo.lock
Cargo.toml
src/main.rs

With this Pull Request, user can execute the following commands:
Use the following command to show the current version of `joshuto`:
```shell
$ joshuto version # same as joshuto --version
joshuto-0.9.5
```
Use the following commands to show shell completions, this will be useful for package maintainers of Linux distributions.
```shell
$ joshuto completions bash  # show shell completion for bash
$ joshuto completions zsh  # show shell completion for zsh
$ joshuto completions fish  # show shell completion for fish
$ joshuto completions elvish  # show shell completion for elvish
$ joshuto completions powershell  # show shell completion for powershell
```
We replaced `structopt` with `clap`, because `structopt` is now in maintenance mode (https://github.com/TeXitoi/structopt#maintenance). All …

Add subcommands

---

src/preview/preview_file.rs

Do not spawn 100s of preview threads when I'm holding the down arrow key in a crowded directory.

fix: add mutex lock to preview threads

---

docs/image_previews/README.md

The image-preview documentation now contains an extra, more explicit statement that the text preview pane must be shown for a file to trigger the shown-hook script.
Should solve #434.

Docs: Add note about text preview for img preview

---

src/ui/tab_list_builder.rs

the redundent `eprintln` could cause UI unusable, so I comment it.

fix: remove the debug info causing the chaos in UI

---

src/commands/change_directory.rs
src/commands/tab_ops.rs
src/main.rs
src/tab/tab_struct.rs
src/util/cwd.rs
src/util/mod.rs

This PR makes joshuto compatible with [wezterm](https://wezfurlong.org/wezterm/) at least with the way it manages the current directory updates.
1. Added a new `cwd` utility module.
2. Centralized CWD updates using the `cwd::set_current_dir` function.
3. Updated to use the `cwd` utility for CWD management.
4. Implements OSC 7: Escape sequences to inform the terminal about the current directory [ref](https://wezfurlong.org/wezterm/shell-integration.html#osc-7-escape-sequence-to-set-the-working-directory).

feat: wezterm cwd compatibility

---

docs/image_previews/kitty.md

I want to use kitty for image preview, so I use the script provided in `docs/image_previews/kitty.md`. 
I found that the script reported an syntax error.
I fixed a syntax error in the image so that the image preview and video thumbnail preview function properly.

Fixed syntax errors for scripts provided in docs/image_previews/kitty.md

---

utils/install.sh

Quick fix for the installation script. Resolve the issue of `printf` interpretation for '%' printing the release notes, uses `echo -e` instead.

fix: skip printf % interpretation

---

config/preview_file.sh

Allows for previewing of whole file metadata even on large files. If there's any kind of concern regarding parsing large files, there's the `max_preview_size` anyway that can be set in `joshuto.toml`

Enable large file support for exiftool

---

src/commands/bookmark.rs

I found a bug where I get the following panic when there are too many bookmarks to fit inside the UI area:
```
thread 'main' panicked at src/commands/bookmark.rs:121:20:
attempt to subtract with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
The y coordinate of the ```ratatui::layout::Rect``` becomes -1 at line 121
I also made sure to truncate the TuiMenu options field to the maximum length, apparently ```area.height as usize - 1```, whenever it exceeds that value

fix overflow bug on bookmark widget when area is too small

---

config/joshuto.toml
config/theme.toml
src/commands/bookmark.rs
src/config/clean/app/config.rs
src/config/clean/app/mod.rs
src/config/clean/bookmarks.rs
src/config/clean/icon/config.rs
src/config/clean/icon/mod.rs
src/config/clean/keymap/config.rs
src/config/clean/keymap/mod.rs
src/config/clean/mimetype/config.rs
src/config/clean/preview/config.rs
src/config/clean/theme/config.rs
src/config/clean/theme/mod.rs
src/config/config_type.rs
src/config/mod.rs
src/error/error_type.rs
src/main.rs

Resolves: #486 
A few things:
* `get_type` trait function is not really needed, but I wanted to tie an actual config with its `ConfigType` value in some way.
* I believe `include_str!("..\\..\\..\\..\\config\\joshuto.toml");` for windows is not needed, and `/` works just as well? I am not sure.
* `get_config` can be moved out of a trait, but with this its usage will be uglier: `let app_config = get_config::<App>()`.
* I thought about adding an option for printing the current config (might be useful for debugging), but let's discuss this first!

Add command for printing embedded configs

---

Cargo.lock
Cargo.toml
src/config/clean/theme/config.rs
src/config/raw/theme/config.rs
src/util/style.rs

This adds support for styling entries using the `LS_COLORS` environment variable. This styling is gated behind a configuration variable. If it's enabled, any other styling for entries based on theme configuration is ignored.
An example configuration line looks like
```toml
lscolors_enabled = true
```
in `theme.toml`.
This change adds a dependency on the [`lscolors`][0] crate. It addresses issue https://github.com/kamiyaa/joshuto/issues/443.
I verified these changes by running
```bash
nix develop --impure
, run
```
on my local machine.
```bash
uname -a
```
```
Linux berrio 6.1.72 #1-NixOS SMP PREEMPT_DYNAMIC Wed Jan 10 16:10:37 UTC 2024 x86_64 GNU/Linux
```
Here's an image of when `lscolors_enabled = true` in `theme.toml`.
Here's an image of when `lscolors_enabled = false` in `theme.toml`. …

feat lscolors support

---

src/commands/sort.rs
src/fs/dirlist.rs

I noticed that changing sort method in directories with many entries might not keep focus on the focused file (and the same goes for parent and child dirs). This patch fixes the issue.

fix: update all lists viewports on sort method change

---

src/io/io_worker.rs

Without this any attempt to trash a file with a `'` in its path results in an error.

fix: escape `'` char in trash operations

---

src/commands/numbered_command.rs

Really simple fix to a quite annoying issue

fix: clear numbered command buffer on cursor move

---

src/config/clean/theme/style.rs
src/config/raw/theme/style.rs
src/ui/widgets/tui_dirlist_detailed.rs
src/util/style.rs

I noticed that the eager evaluation of prefix width introduced in 1822104 ignores the line number part, which is pushed to prefix later.

fix: restore line numbers

---

docs/configuration/keymap.toml.md
src/commands/sort.rs
src/key_command/command.rs
src/key_command/impl_appcommand.rs
src/key_command/impl_appexecute.rs
src/key_command/impl_comment.rs
src/key_command/impl_display.rs
src/key_command/impl_from_str.rs

This can be useful to get to a specific order with just a command without the need of toggling reverse each time, for example when I switch to `mtime` sort I often want newer files on top, which is reversed.

feat: add `--reverse` flag to sort methods

---

docs/configuration/keymap.toml.md
src/commands/tab_ops.rs
src/context/tab_context.rs
src/key_command/command.rs
src/key_command/impl_appexecute.rs
src/key_command/impl_from_str.rs
src/run.rs

This changes `new_tab`'s default behavior, putting the new tab at current tab index + 1, adding the `--last` flag to push the new tab to the end.

feat: add `--last` option to `new_tab` command

---

src/commands/custom_search.rs
src/commands/sub_process.rs

This allows to run the file under cursor (if executable) with `:shell %s`, `:shell ./%s` or `:shell %p`.
I also fixed a bug introduced in #495 which caused a panic when trying to run a file that doesn't exist or a non-executable file.

feat: add support for %s and %p as first argument to subprocess commands

---

src/commands/fzf.rs
src/commands/show_tasks.rs

I noticed that switching to fzf or task view with an image preview visible, it remains there covering part of the view, so this fixes the issue.

fix: hide image preview in fzf and task view

---

src/key_command/constants.rs
src/key_command/impl_completion.rs
src/key_command/mod.rs
src/key_command/traits.rs
src/ui/views/tui_textfield.rs

As anticipated in #502, this is my implementation of a comprehensive autocompletion for each command (closes #180), which can be of 4 kinds:
- Any file
- Directories (`cd`, `new_tab`)
- Executable files (`shell`, `spawn`)
- A custom list of arguments or flags
More details in the comments below.

feat: comprehensive autocompletion for each command

---

Cargo.lock
Cargo.toml
docs/configuration/joshuto.toml.md
docs/image_previews/README.md
src/config/clean/app/preview/config.rs
src/config/raw/app/display/preview.rs
src/context/app_context.rs
src/context/preview_context.rs

This implements a cache for thumbnails and image previews for non-image file formats, like videos and PDFs.
This patch extends the inbuilt image preview feature (285df85) by integrating the `allmytoes` crate and using its thumbnails instead of the actual file being previewed.
The image-preview feature uses the XDG-(freedesktop.org-) specified thumbnail-cache to re-use existing thumbs and to store newly created thumbs.
(https://specifications.freedesktop.org/thumbnail-spec/thumbnail-spec-latest.html)
This increases performance for the image-preview because the preview does not need to load the full-sized version of the image and does not need to scale it down every time, once the thumbnail has been created. Also, thumbnails are now shared with other programs that use the XDG-thumb cache. …

XDG-thumb for preview & thumbs for non-image files

---

docs/configuration/joshuto.toml.md
src/config/clean/app/display/line_mode.rs
src/config/raw/app/display/config.rs
src/fs/metadata.rs
src/key_command/impl_comment.rs
src/ui/widgets/tui_dirlist_detailed.rs
src/ui/widgets/tui_footer.rs
src/util/format.rs

1. refact the `LineMode` struct, make it more flexible for user to change the order of the item in line mode
2. add more line more in #524

feat: more linemode

---

src/commands/preview_cursor_move.rs
src/event/process_event.rs

- Add file preview scrolling with the mouse.
- Limit file preview scrolling to the last 3 lines to avoid scrolling way past the last line of the file.
Closes #535

feat: Add mouse scrolling in file preview

---

Cargo.lock
Cargo.toml
config/joshuto.toml
docs/configuration/joshuto.toml.md
src/config/raw/app/display/preview.rs

add `bytesize` for parse the bytes string
just change the deserialize function for `max_preview_size` and change the default config to "2MiB" and change the doc

Feat: Human readable preview size

---

config/theme.toml
docs/image_previews/README.md
src/config/theme/mod.rs
src/config/theme/theme_raw.rs
src/types/state/app_state.rs

https://github.com/benjajaja/ratatui-image/issues/21
Due to ratatui's immediate-mode nature, the cells behind the image must be "skipped" so that nothing draws over the image. In other words, the cells behind the image still have whatever was drawn last time before they were marked skipped for the image. Thus, the image must always fill the cells/area, and the frame cannot be made transparent.
This PR makes the background color configurable via theme.toml. It could also be done via `joshuto.toml`, which is what I initially did, so I could revert to that. I am not sure which is better, the goal here is essentially to make previews look good in terminals with white background, but it actually also applies to any terminal theme background color that isn't pitch black.
Closes #521

configure preview image background color via theme.toml

---

config/joshuto.toml
src/types/option/display.rs
src/ui/views/mod.rs
src/ui/views/tui_minimal_view.rs
src/ui/views/tui_view.rs

This adds a new display mode referred to as `minimal`. 
[It does exactly what it says on the tin](https://en.wikipedia.org/wiki/Does_exactly_what_it_says_on_the_tin) - basically the current tab content is rendered full size (no miller columns like in `default`, no multipanes like in `hsplit`).
This is similar to the `multipane` view in ranger when there is only one tab.
Disclaimer: I was personally missing this feature and built it by copy-pasting and cutting down existing code - not really knowing Rust. I hope I didn't miss anything important.

Add minimal display mode

---

src/main.rs
src/types/command/impl_completion.rs
src/types/command/impl_from_str.rs

- According to [the documentation of std::fmt](https://doc.rust-lang.org/std/fmt/index.html#sign0):
> *\+* - This is intended for numeric types and indicates that the sign should always be printed. By default only the negative sign of signed values is printed, and the sign of positive or unsigned values is omitted. This flag indicates that the correct sign (+ or -) should always be printed.

refactor: replace manual sign detection with format spec "+"

---

docs/configuration/keymap.toml.md
src/commands/sub_process.rs

Implement a new keyword for spawn and shell commands, `%d`, allowing the use of current working directory as parameter instead of the selected file(s).
Example: to open a new alacritty terminal in the current folder:
```toml
keymap = [ // ..
{ keys = [ "O" ], commands = ["spawn alacritty --working-directory %d"] }
]
```
Related to #541 and #456

feat: add option to use current working directory with the %d keyword
